# Generated by Django 2.2.1 on 2019-07-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=24)),
                ('l_name', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=48, unique=True)),
                ('login_method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=24)),
                ('l_name', models.CharField(max_length=24)),
                ('record_date', models.DateField()),
            ],
        ),
    ]
