# Generated by Django 2.2.1 on 2019-07-09 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0002_auto_20190709_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=None, to='RetinaScrApp.Doctor'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=None, to='RetinaScrApp.Doctor'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='patient',
            field=models.ForeignKey(default=None, on_delete=None, to='RetinaScrApp.Patient'),
        ),
    ]
