# Generated by Django 2.2.1 on 2019-07-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0004_auto_20190709_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='source_code',
            field=models.CharField(default=None, max_length=20000),
        ),
    ]
