# Generated by Django 2.2.1 on 2019-07-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0005_algorithm_source_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fovea_pref',
            field=models.CharField(default='default', max_length=24),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lesion_pref',
            field=models.CharField(default='default', max_length=24),
        ),
        migrations.AddField(
            model_name='doctor',
            name='optic_pref',
            field=models.CharField(default='default', max_length=24),
        ),
        migrations.AddField(
            model_name='doctor',
            name='vessel_pref',
            field=models.CharField(default='default', max_length=24),
        ),
    ]
