# Generated by Django 2.2.1 on 2019-07-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0006_auto_20190710_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='default', max_length=48),
        ),
    ]
