# Generated by Django 2.2.1 on 2019-07-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0007_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doc_username',
            field=models.CharField(default='ZZZZZZZZZZ', max_length=10),
        ),
    ]
