# Generated by Django 2.2.1 on 2019-07-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0009_auto_20190718_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='algo_status',
        ),
    ]
