# Generated by Django 2.2.1 on 2019-07-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RetinaScrApp', '0011_auto_20190718_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='last_modified',
        ),
    ]
